services:
  go:
    container_name: go
    image: cryptoviz/scraper:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app             # Monte le répertoire local dans le conteneur
      - /app/tmp           # Emplacement temporaire pour le fichier binaire compilé
    working_dir: /app/src  # Répertoire de travail pour le code source
    ports:
      - "8080:8080"        # Expose le port 8080 si nécessaire