services:
  go:
    container_name: go-scraper
    image: cryptoviz/scraper:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app             # Monte le répertoire local dans le conteneur
    working_dir: /app      # Répertoire de travail pour le code source